# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Ensure the entrypoint is executable
RUN chmod +x index.js

# Expose any ports if necessary (not required for stdio transport)

CMD ["node", "index.js", "run"]
